### PR TITLE
Fix archivation issues

### LINKED ISSUE #46: Fix a problem with old vacancies
## Describe the bug

We have a problem with some vacancies was created half of a year ago. It's incorrect and we need to fix it

## Expected behavior

We close vacancy after 2 or 4 weeks.

## Screenshots

Screenshot 2019-10-03 at 18 50 59

### PR DESCRIPTION
**Pull request by Nulevaya**
Tried to fix #46 by removing `archived` field from vacancies and making `archived_at` responsible for that logic.

### CODE REVIEW

File: lib/core/queries/vacancy.rb [hunk 1]
```diff
@@ -22,7 +22,8 @@ def pager_for_all_with_contact(limit:, page:)
 
     def all_with_contact_relation(limit:, page:)
       repo.aggregate(:contact)
-          .where(published: true, archived: false, deleted_at: nil)
+          .where(published: true, deleted_at: nil)
+          .where('archived_at > ?', Date.today)
```
Comment (davydovanton) [inline lib/core/queries/vacancy.rb]: Отличное решение!
